using System;
using System.Collections.Generic;
using System.Text;

namespace YokiFrame
{
    /// <summary>
    /// AudioKit 音频 ID 代码生成器。
    /// 负责把扫描结果转换为常量定义和可选的路径映射代码。
    /// </summary>
    internal static class AudioIdCodeGenerator
    {
        /// <summary>
        /// 根据扫描结果生成完整的 C# 源码文本。
        /// </summary>
        public static string Generate(
            List<AudioFileInfo> files,
            string namespaceName,
            string className,
            bool generatePathMap,
            bool groupByFolder)
        {
            var sb = new StringBuilder(4096);

            WriteHeader(sb);
            WriteUsings(sb, generatePathMap);

            sb.AppendLine($"namespace {namespaceName}");
            sb.AppendLine("{");

            WriteAudioIdsClass(sb, files, className, groupByFolder);

            if (generatePathMap)
            {
                sb.AppendLine();
                WriteAudioPathsClass(sb, files, className);
            }

            sb.AppendLine("}");
            return sb.ToString();
        }

        /// <summary>
        /// 写入自动生成文件头。
        /// </summary>
        private static void WriteHeader(StringBuilder sb)
        {
            var timestamp = DateTime.Now.ToString("yyyy-MM-dd HH:mm:ss");
            sb.AppendLine("//------------------------------------------------------------------------------");
            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("//     This code was generated by YokiFrame AudioKit.");
            sb.AppendLine($"//     Generated at: {timestamp}");
            sb.AppendLine("//");
            sb.AppendLine("//     Changes to this file may cause incorrect behavior and will be lost if");
            sb.AppendLine("//     the code is regenerated.");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine("//------------------------------------------------------------------------------");
            sb.AppendLine();
        }

        /// <summary>
        /// 根据生成选项写入所需的 using 语句。
        /// </summary>
        private static void WriteUsings(StringBuilder sb, bool generatePathMap)
        {
            if (!generatePathMap)
            {
                return;
            }

            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine();
        }

        /// <summary>
        /// 写入音频 ID 常量类。
        /// </summary>
        private static void WriteAudioIdsClass(StringBuilder sb, List<AudioFileInfo> files, string className, bool groupByFolder)
        {
            sb.AppendLine("    /// <summary>");
            sb.AppendLine("    /// 音频 ID 常量定义");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine($"    public static class {className}");
            sb.AppendLine("    {");

            if (groupByFolder)
            {
                WriteGroupedConstants(sb, files);
            }
            else
            {
                WriteUngroupedConstants(sb, files);
            }

            sb.AppendLine("    }");
        }

        /// <summary>
        /// 按文件夹分组写入音频常量。
        /// </summary>
        private static void WriteGroupedConstants(StringBuilder sb, List<AudioFileInfo> files)
        {
            var groups = new Dictionary<string, List<AudioFileInfo>>();

            foreach (var file in files)
            {
                var category = string.IsNullOrEmpty(file.FolderCategory) ? "General" : file.FolderCategory;
                if (!groups.TryGetValue(category, out var list))
                {
                    list = new List<AudioFileInfo>();
                    groups[category] = list;
                }

                list.Add(file);
            }

            var isFirst = true;
            foreach (var kvp in groups)
            {
                if (!isFirst)
                {
                    sb.AppendLine();
                }

                isFirst = false;
                sb.AppendLine($"        #region {kvp.Key}");
                sb.AppendLine();

                foreach (var file in kvp.Value)
                {
                    sb.AppendLine("        /// <summary>");
                    sb.AppendLine($"        /// {file.Name}");
                    sb.AppendLine("        /// </summary>");
                    sb.AppendLine($"        public const int {file.ConstantName} = {file.Id};");
                    sb.AppendLine();
                }

                sb.AppendLine("        #endregion");
            }
        }

        /// <summary>
        /// 以扁平方式写入音频常量。
        /// </summary>
        private static void WriteUngroupedConstants(StringBuilder sb, List<AudioFileInfo> files)
        {
            foreach (var file in files)
            {
                sb.AppendLine("        /// <summary>");
                sb.AppendLine($"        /// {file.Name}");
                sb.AppendLine("        /// </summary>");
                sb.AppendLine($"        public const int {file.ConstantName} = {file.Id};");
                sb.AppendLine();
            }
        }

        /// <summary>
        /// 写入音频 ID 到路径的映射类。
        /// </summary>
        private static void WriteAudioPathsClass(StringBuilder sb, List<AudioFileInfo> files, string idsClassName)
        {
            sb.AppendLine("    /// <summary>");
            sb.AppendLine("    /// 音频路径映射");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine("    public static class AudioPaths");
            sb.AppendLine("    {");
            sb.AppendLine("        /// <summary>");
            sb.AppendLine("        /// 音频 ID 到路径的映射字典");
            sb.AppendLine("        /// </summary>");
            sb.AppendLine("        public static readonly Dictionary<int, string> Map = new()");
            sb.AppendLine("        {");

            for (var i = 0; i < files.Count; i++)
            {
                var file = files[i];
                var comma = i < files.Count - 1 ? "," : "";
                sb.AppendLine($"            {{ {idsClassName}.{file.ConstantName}, \"{file.Path}\" }}{comma}");
            }

            sb.AppendLine("        };");
            sb.AppendLine();
            sb.AppendLine("        /// <summary>");
            sb.AppendLine("        /// 根据音频 ID 获取路径");
            sb.AppendLine("        /// </summary>");
            sb.AppendLine("        public static string GetPath(int audioId)");
            sb.AppendLine("        {");
            sb.AppendLine("            return Map.TryGetValue(audioId, out var path) ? path : null;");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
        }
    }
}
