
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using JSONNode = SimpleJSON.JSONNode;
using JSONNodeType = SimpleJSON.JSONNodeType;


namespace cfg
{
public partial struct FormalDamageMatchup
{
    public FormalDamageMatchup(JSONNode _buf) 
    {
        { if(!_buf["SourceTag"].IsNumber) { throw new SerializationException(); }  SourceTag = _buf["SourceTag"]; }
        { if(!_buf["TargetTag"].IsNumber) { throw new SerializationException(); }  TargetTag = _buf["TargetTag"]; }
        { if(!_buf["Multiplier"].IsNumber) { throw new SerializationException(); }  Multiplier = _buf["Multiplier"]; }
        { if(!_buf["Presentation"].IsNumber) { throw new SerializationException(); }  Presentation = _buf["Presentation"]; }
    }

    public static FormalDamageMatchup DeserializeFormalDamageMatchup(JSONNode _buf)
    {
        return new FormalDamageMatchup(_buf);
    }

    public readonly int SourceTag;
    public readonly int TargetTag;
    public readonly float Multiplier;
    public readonly int Presentation;
   

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "SourceTag:" + SourceTag + ","
        + "TargetTag:" + TargetTag + ","
        + "Multiplier:" + Multiplier + ","
        + "Presentation:" + Presentation + ","
        + "}";
    }
}
}

